#!/usr/bin/env zsh

# Generate a random UUID (works on macOS + most Linux distros with uuidgen)
USER_ID=$(uuidgen | tr '[:upper:]' '[:lower:]')

echo "user_$USER_ID"
http POST http://localhost:8080/api/v1/orders/ \
  user_id="user_$USER_ID" \
  total_amount:=100.0 \
  currency=USD \
  shipping_address="DLF PHASE 2, GURGAON" \
  items:='[{"product_id":"SKU-123","quantity":2,"price":50.0}]'
